config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  # Login routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: :log_in
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Password routes
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'
  # get 'password/reset', to: 'password_resets#new'
  # post 'password/reset', to: 'password_resets#create'
  # get 'password/reset/edit', to: 'password_resets#edit'
  # patch 'password/reset/edit', to: 'password_resets#update'

  # Slangs routes
  get 'slangs/new', to: 'slangs#new', as: :slang_new
  post 'slangs/new', to: 'slangs#create', as: :slang_create
  post 'slangs/like', to: 'slangs#like', as: :slang_like

  # Searches
  get 'search', to: 'search#show'

  # User routes
  get 'user/:username', to: 'user#show', username: %r{[^/]+}
  get 'profile/settings', to: 'user#settings', as: :settings
  patch 'profile/settings', to: 'user#settings_update', as: :settings_update

  # Admin routes
  get 'admin', to: 'admin#show', as: :admin
  patch 'admin/slang/:slang_id/approve/', to: 'admin#approve', as: :admin_slang_approve
  delete 'admin/slang/:slang_id/remove/', to: 'admin#destroy', as: :admin_slang_remove
end

app/views/admin/show.html.erb
<div class="container">
    <p>
        <%= Slang.where(is_approved: false).count %> unapproved slangs
    </p>
    <% @slangs.each do |slang_content| %>
        <%= button_to "Approve", admin_slang_approve_path(slang_content), form_class: 'd-inline', class: 'btn btn-success', method: :patch %>
        <%= button_to "Remove", admin_slang_remove_path(slang_content), form_class: 'd-inline', class: 'btn btn-danger', method: :delete %>
        <%= render '/shared/slang', slang_content: slang_content %>
    <% end %>
    <%== pagy_bootstrap_nav(@pagy) %>
</div>