config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  # Login routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: :log_in
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Password routes
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'
  # get 'password/reset', to: 'password_resets#new'
  # post 'password/reset', to: 'password_resets#create'
  # get 'password/reset/edit', to: 'password_resets#edit'
  # patch 'password/reset/edit', to: 'password_resets#update'

  # Slangs routes
  get 'slangs/new', to: 'slangs#new', as: :slang_new
  post 'slangs/new', to: 'slangs#create', as: :slang_create
  post 'slangs/like', to: 'slangs#like', as: :slang_like

  # Searches
  get 'search', to: 'search#show'

  # User routes
  get 'user/:username', to: 'user#show', username: %r{[^/]+}
  get 'profile/settings', to: 'user#settings', as: :settings
  patch 'profile/settings', to: 'user#settings_update', as: :settings_update

  # Admin routes
  get 'admin', to: 'admin#show', as: :admin
  patch 'admin/slang/:slang_id/approve/', to: 'admin#approve', as: :admin_slang_approve
  delete 'admin/slang/:slang_id/remove/', to: 'admin#destroy', as: :admin_slang_remove
end

app/models/slang.rb
class Slang < ApplicationRecord
  belongs_to :user

  has_many :votes
  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      where('word LIKE ? AND is_approved = true', "%#{pattern}%")
    end
  end
end

app/controllers/slangs_controller.rb
# Current.user.id
class SlangsController < ApplicationController
  protect_from_forgery with: :null_session

  def new
    @slang = Current.user.slangs.new
  end

  def create
    @slang = Current.user.slangs.new(slang_params)
    if @slang.save
      redirect_to root_path, notice: 'Successfully created post'
    else
      redirect_to root_path, alert: @post.errors.messages
    end
  end

  def like
    return redirect_to log_in_path, notice: 'You need to sign in to vote' unless Current.user

    slang_like = Current.user.votes.where(vote_params).first_or_initialize
    if params[:is_liked] == 'true' || params[:is_unliked] == 'true'
      slang_like.destroy
      redirect_back fallback_location: root_path, notice: 'Vote Removed'
    elsif slang_like.id.nil? || slang_like.id
      slang_like.upvote = params[:is_liked] ? true : false
      slang_like.update(vote_params)
      redirect_back fallback_location: root_path, notice: 'Vote Added'
    else
      # Shouldn't be reaching here
      redirect_back fallback_location: root_path, notice: 'Vote Removed'
    end
  end

  private

  def slang_params
    params.require(:slang).permit(:word, :definition)
  end

  def vote_params
    params.require(:vote).permit(:slang_id, :value)
  end
end

app/views/slangs/new.html.erb
<div class="signup-form">
    <%= form_with model: @slang, url: slang_create_path do |f| %>
        <div class="row">
            <div class="col-8 offset-4">
                <h2>Add Slang</h2>
            </div>
        </div>
        <div class="form-group mb-3">
            <%= f.label :word, 'Word', class: 'col-form-label col-4' %>
            <%= f.text_field :word, class: 'form-control', required: true %>
        </div>
        <div class="form-group mb-3">
            <%= f.label :definition, 'Definition', class: 'col-form-label col-4' %>
            <%= f.text_area :definition, class: 'form-control', required: true, placeholder: 'Type your definition here...' %>
        </div>
        <div class="form-group mb-3 text-center">
            <%= f.submit 'Post', class: 'btn btn-primary btn-lg w-50' %>
        </div>
    <% end %>
</div>