config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  # Login routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: :log_in
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Password routes
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'
  # get 'password/reset', to: 'password_resets#new'
  # post 'password/reset', to: 'password_resets#create'
  # get 'password/reset/edit', to: 'password_resets#edit'
  # patch 'password/reset/edit', to: 'password_resets#update'

  # Slangs routes
  get 'slangs/new', to: 'slangs#new', as: :slang_new
  post 'slangs/new', to: 'slangs#create', as: :slang_create
  post 'slangs/like', to: 'slangs#like', as: :slang_like

  # Searches
  get 'search', to: 'search#show'

  # User routes
  get 'user/:username', to: 'user#show', username: %r{[^/]+}
  get 'profile/settings', to: 'user#settings', as: :settings
  patch 'profile/settings', to: 'user#settings_update', as: :settings_update

  # Admin routes
  get 'admin', to: 'admin#show', as: :admin
  patch 'admin/slang/:slang_id/approve/', to: 'admin#approve', as: :admin_slang_approve
  delete 'admin/slang/:slang_id/remove/', to: 'admin#destroy', as: :admin_slang_remove
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-white mt-auto">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.twitter.com" role="button" style="width: 40px; height: 40px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
          </svg>
        </a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.instagram.com" role="button" style="width: 40px; height: 40px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
          </svg>
        </a>
  
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.linkedin.com" role="button" style="width: 40px; height: 40px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
          </svg>
        </a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.github.com" role="button" style="width: 40px; height: 40px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
        </a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="">Link</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/shared/_header.html.erb
<header class="py-3 mb-3 border-bottom bg-dark">
    <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 60px 2fr;">
        <%= link_to 'Home', root_path, class: 'mb-2 mb-lg-0 link-light text-decoration-none' %>

      <div class="d-flex align-items-center">
        <%= form_with(url: search_path, method: :get, class: 'w-100 me-3') do |f| %>
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="q" value="<%= params[:q] %>">
        <% end %>
        <% if Current.user%>
            <div class="flex-shrink-0 dropdown">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag 'profile_image.png', height: 32, width: 32, class: 'rounded-circle' %>
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                    <% if Current.user.is_admin %>
                        <li>
                            <%= button_to 'Admin', admin_path, method: :get, class: 'dropdown-item' %>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                    <% end %>
                    <li><a class="dropdown-item" href="<%= slang_new_path %>">New slang...</a></li>
                    <li><a class="dropdown-item" href="/user/<%= Current.user.username %>">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        <%= button_to 'Sign out', logout_path, method: :delete, class: 'dropdown-item' %>
                    </li>
                </ul>
            </div>
        <% else %>
            <%= link_to 'Sign Up', sign_up_path, class: 'link-light text-decoration-none text-nowrap me-2' %>
            <%= link_to 'Login', sign_in_path, class: 'link-light text-decoration-none text-nowrap' %>
        <% end %>
      </div>
    </div>
</header>

app/views/shared/_slang.html.erb
<div class="card mb-4 rounded-0">
    <div class="card-body">
        <h2 class="card-title">
            <a href="/search?q=<%= slang_content.word %>" class="text-decoration-none">
                <%= slang_content.word %>
            </a>
            <% if !slang_content.is_approved %>
                <i class="text-muted" style="font-size: 0.8rem;">Waiting for approval...</i>
            <% end %>
        </h2>
        <p class="card-text"><%= slang_content.definition %></p>
        <div>by <a href="user/<%= slang_content.user.username %>" class="text-decoration-none"><%= slang_content.user.username %></a> - <%= slang_content.created_at.strftime("%d %B %Y") %></div>
        <div>
            <%= form_with model: @vote, url: slang_like_path, class: 'd-inline' do |f| %>
                <%= f.hidden_field :slang_id, value: slang_content.id  %>
                <% if Current.user && Vote.find_by(user_id: Current.user.id, slang_id: slang_content.id, upvote: true) %>
                    <input type="hidden" name="is_liked" value="true">
                    <button class="btn upvote-button" type="submit" name="commit">
                        <span class="position-relative">
                            <div class="position-absolute shadow-hover"></div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-up-fill" viewBox="0 0 16 16">
                                <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                            </svg>
                        </span>
                        &nbsp;
                        <%= slang_content.votes.where(upvote: true).count.to_s %>
                    </button>
                <% else %>
                    <input type="hidden" name="is_liked">
                    <button class="btn upvote-button" type="submit" name="commit">
                        <span class="position-relative">
                            <div class="position-absolute shadow-hover"></div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 16 16">
                                <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
                            </svg>
                        </span>
                        &nbsp;
                        <%= slang_content.votes.where(upvote: true).count.to_s %>
                    </button>
                <% end %>
            <% end %>
            <%= form_with model: @vote, url: slang_like_path, class: 'd-inline' do |f| %>
                <%= f.hidden_field :slang_id, value: slang_content.id  %>
                <% if Current.user && Vote.find_by(user_id: Current.user.id, slang_id: slang_content.id, upvote: false) %>
                    <input type="hidden" name="is_unliked" value="true">
                    <button class="btn downvote-button" type="submit" name="commit">
                        <span class="position-relative">
                            <div class="position-absolute shadow-hover"></div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                            </svg>
                        </span>
                        &nbsp;
                        <%= slang_content.votes.where(upvote: false).count.to_s %>
                    </button>
                <% else %>
                    <input type="hidden" name="is_unliked">
                    <button class="btn downvote-button" type="submit" name="commit">
                        <span class="position-relative">
                            <div class="position-absolute shadow-hover"></div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down" viewBox="0 0 16 16">
                                <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z"/>
                            </svg>
                        </span>
                        &nbsp;
                        <%= slang_content.votes.where(upvote: false).count.to_s %>
                    </button>
                <% end %>
            <% end %>
        </div>
    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
</div>