config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  # Login routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: :log_in
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Password routes
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'
  # get 'password/reset', to: 'password_resets#new'
  # post 'password/reset', to: 'password_resets#create'
  # get 'password/reset/edit', to: 'password_resets#edit'
  # patch 'password/reset/edit', to: 'password_resets#update'

  # Slangs routes
  get 'slangs/new', to: 'slangs#new', as: :slang_new
  post 'slangs/new', to: 'slangs#create', as: :slang_create
  post 'slangs/like', to: 'slangs#like', as: :slang_like

  # Searches
  get 'search', to: 'search#show'

  # User routes
  get 'user/:username', to: 'user#show', username: %r{[^/]+}
  get 'profile/settings', to: 'user#settings', as: :settings
  patch 'profile/settings', to: 'user#settings_update', as: :settings_update

  # Admin routes
  get 'admin', to: 'admin#show', as: :admin
  patch 'admin/slang/:slang_id/approve/', to: 'admin#approve', as: :admin_slang_approve
  delete 'admin/slang/:slang_id/remove/', to: 'admin#destroy', as: :admin_slang_remove
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # validates email
  validates :username, presence: true, uniqueness: true, length: { minimum: 1, maximum: 15 }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  has_many :slangs
  has_many :votes
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find_by(username: params[:username].downcase)
    @pagy, @slangs = pagy(Slang.where(user_id: @user.id).where(is_approved: true).order(created_at: :desc))
    return unless Current.user && (Current.user.id == @user.id || Current.user.is_admin)

    @pagy, @slangs = pagy(Slang.where(user_id: @user.id).order(created_at: :desc))
  end

  def settings
    @user = Current.user
  end

  def settings_update
    if Current.user.update(user_params)
      redirect_to settings_path, notice: 'Settings Updated'
    else
      redirect_to settings_path, notice: 'Issues'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/views/user/settings.html.erb
<div class="signup-form">
    <%= form_with model: @user, url: settings_update_path do |f| %>
        <div class="row">
            <div class="text-center">
                <h2>Change Username</h2>
            </div>
        </div>
        <div class="form-group mb-3">
            <%= f.label :username, 'Username', class: 'col-form-label col-4' %>
            <%= f.text_field :username, class: 'form-control', required: true %>
        </div>
        <div class="form-group mb-3 text-center">
            <%= f.submit 'Update', class: 'btn btn-primary btn-lg w-50' %>
        </div>
    <% end %>
</div>

app/views/user/show.html.erb
<div class="container">
    <% if Current.user && (@user.id == Current.user.id) %>
        <div>
            <%= link_to 'Edit Username', settings_update_path %>
        </div>
        <div>
            <%= link_to 'Edit Password', edit_password_path %>
        </div>
    <% end %>
    <p>
        <%= @slangs.count %> results by <b><%= @user.username %></b>
    </p>
    <% @slangs.each do |slang_content| %>
        <%= render '/shared/slang', slang_content: slang_content %>
    <% end %>
    <%== pagy_bootstrap_nav(@pagy) %>
</div>